---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/rust-skeleton.git
    branch: master
- name: image
  type: docker-image
  source:
    repository: dolphm/ubuntu-latest-rust-nightly

jobs:
- name: build
  plan:
  - get: repo
    trigger: true
  - get: image
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/ubuntu-latest-rust-nightly
      inputs:
      - name: repo
      run:
        path: repo/ci/build.sh
